#!/bin/bash
intltool-extract --type=gettext/glade usr/share/hamonikr/hamonikr-report/hamonikr-report.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=hamonikr-report.pot usr/lib/hamonikr/hamonikr-report/*.py generate_desktop_files usr/share/hamonikr/hamonikr-report/hamonikr-report.ui.h usr/share/hamonikr/hamonikr-report/reports/*/*.py
rm -f usr/share/hamonikr/hamonikr-report/hamonikr-report.ui.h
