#!/bin/bash
sudo rm -rf /usr/lib/hamonikr/hamonikr-report
sudo rm -rf /usr/share/hamonikr/hamonikr-report/reports/900_drivers
sudo rm -rf /usr/share/hamonikr/hamonikr-report/reports/060_timeshift-no-setup
sudo rm -rf /usr/share/hamonikr/hamonikr-report/reports/070_new-release
sudo rm -rf /usr/share/hamonikr/hamonikr-report/reports/500_install-language-packs
sudo rm -rf /usr/share/hamonikr/hamonikr-report/reports/045_xappstatusapplet-missing
sudo rm -rf /usr/share/hamonikr/hamonikr-report/reports/050_install-media-codecs
sudo rm -rf /usr/share/hamonikr/hamonikr-report/reports/080_release-eol
sudo rm -rf /usr/share/hamonikr/hamonikr-report/hamonikr-report.ui
sudo cp -R usr /
hamonikr-report
